/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-11-08 09:09:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Loggin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ADMIN/Desktop/carpetas/Sistema%20de%20Denuncias%20Municipalidad%20de%20Ica/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Municipalidad_Provincial%20de%20ICA-Navegable/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1607542950000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1633429499910L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\" integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"container\" style=\" margin: 2% auto\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class= \"izquierda\" style=\"float: left; margin: 0 0 0 100px; width: 40%; height: 30%\">\r\n");
      out.write("  \t\t\t\t<img src=\"img/Logo.png\" id= \"logo\" \tstyle=\"width: 100%; height: 100%;\">\r\n");
      out.write("  \t\t\t\t<br>\r\n");
      out.write("  \t\t\t\t<div style=\"float: left; margin: 10px 0 0 20px\">\r\n");
      out.write("  \t\t\t\t\t\t<h6 style=\"color: #A19B9A\">Bienvenido ciudadano iqueño(a),</h6>\r\n");
      out.write("  \t\t\t\t\t\t<h6 style=\"color: #A19B9A\">esta es una aplicacion web donde puedes</h6>\r\n");
      out.write("  \t\t\t\t\t\t<h6 style=\"color: #A19B9A\">gestionar tu denuncia.</h6>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form class=\"user\" data-toggle=\"validator\" role=\"form\" action=\"sesionserv?accion=INICIAR\"  method=\"post\" id=\"iniciarSesion\"  >\r\n");
      out.write("\t\t\t<div class=\"derecha\" style=\"float: right; margin: 100px 80px 0 0\">\r\n");
      out.write("\t\t\t\t<div class=\"CrearCuenta\" style=\" margin: 0 0 0 300px\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"crearCuenta.jsp\"><h6>Crear cuenta</h6></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"campos\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" required=\"required\" pattern=\"{1,8}\" size=\"50\" placeholder=\"DNI Usuario\" onkeypress='validate(event)' name=\"login\" style=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" size=\"50\" required=\"required\" pattern=\"{1,30}\" placeholder=\"Contraseña\" name=\"clave\" style=\"margin: 20px 0 0 0\"/>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\" margin: 10px 0 0 0;\"> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"recuperarContraseña.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\"float: left\">¿Olvidó su contraseña?</h6></a>\r\n");
      out.write("\t\t\t\t\t\t <button type=\"submit\" class=\"btn btn-outline-secondary\" id=\"btnIniciar\" style=\" float: right;\"><span class=\"boton\">Iniciar Sesion</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float: left; margin: 10px 0 0 20px\" >\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\"color: #A19B9A\">Ingresa tu usuario y contraseña</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\"color: #A19B9A\">Luego da click en \"Iniciar sesion\" o presione \"Enter\"</h6>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">¡Tu contraseña es importante!</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">Recuerda que siempre debes tener:</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">-Minimo 8 caracteres, maximo 20.</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">-Una mayuscula y una minuscula.</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">-Un numero.</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 style=\" color: #7B7A7A\">-No debe contener informacion tuya.</h6>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function validate(evt) {\r\n");
      out.write("\t  var theEvent = evt || window.event;\r\n");
      out.write("\r\n");
      out.write("\t  // Handle paste\r\n");
      out.write("\t  if (theEvent.type === 'paste') {\r\n");
      out.write("\t      key = event.clipboardData.getData('text/plain');\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t  // Handle key press\r\n");
      out.write("\t      var key = theEvent.keyCode || theEvent.which;\r\n");
      out.write("\t      key = String.fromCharCode(key);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  var regex = /[0-9]|\\./;\r\n");
      out.write("\t  if( !regex.test(key) ) {\r\n");
      out.write("\t    theEvent.returnValue = false;\r\n");
      out.write("\t    if(theEvent.preventDefault) theEvent.preventDefault();\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Loggin.jsp(41,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"alert alert-light alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("\t\t\t  <strong></strong><i class=\"fas fa-exclamation-circle alerta\"></i>\r\n");
          out.write("\t\t\t  <h6>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h6>\r\n");
          out.write("\t\t\t \r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
